// Generated by CIRCT firtool-1.62.1
module MultiPortFIFO(
  input        clock,
               reset,
  input  [7:0] io_enq_1_bits,
  output       io_deq_0_valid,
  output [7:0] io_deq_0_bits,
  output       io_deq_1_valid,
  output [7:0] io_deq_1_bits,
  output       io_deq_2_valid,
  output [7:0] io_deq_2_bits,
  input        io_deq_3_ready,
  output       io_deq_3_valid,
  output [7:0] io_deq_3_bits
);

  wire       _queue_io_deq_valid;
  wire [7:0] _queue_io_deq_bits;
  Queue32_UInt8 queue (
    .clock        (clock),
    .reset        (reset),
    .io_enq_bits  (io_enq_1_bits),
    .io_deq_ready (io_deq_3_ready),
    .io_deq_valid (_queue_io_deq_valid),
    .io_deq_bits  (_queue_io_deq_bits)
  );
  assign io_deq_0_valid = _queue_io_deq_valid;
  assign io_deq_0_bits = _queue_io_deq_bits;
  assign io_deq_1_valid = _queue_io_deq_valid;
  assign io_deq_1_bits = _queue_io_deq_bits;
  assign io_deq_2_valid = _queue_io_deq_valid;
  assign io_deq_2_bits = _queue_io_deq_bits;
  assign io_deq_3_valid = _queue_io_deq_valid;
  assign io_deq_3_bits = _queue_io_deq_bits;
endmodule

