// Generated by CIRCT firtool-1.62.1
module rat(
  input        clock,
               reset,
  output       io_read_0_valid,
  output [7:0] io_read_0_bits,
  output       io_read_1_valid,
  output [7:0] io_read_1_bits,
  output       io_read_2_valid,
  output [7:0] io_read_2_bits,
  input        io_read_3_ready,
  output       io_read_3_valid,
  output [7:0] io_read_3_bits,
  input  [7:0] io_write_1_bits
);

  MultiPortFIFO fifo (
    .clock          (clock),
    .reset          (reset),
    .io_enq_1_bits  (io_write_1_bits),
    .io_deq_0_valid (io_read_0_valid),
    .io_deq_0_bits  (io_read_0_bits),
    .io_deq_1_valid (io_read_1_valid),
    .io_deq_1_bits  (io_read_1_bits),
    .io_deq_2_valid (io_read_2_valid),
    .io_deq_2_bits  (io_read_2_bits),
    .io_deq_3_ready (io_read_3_ready),
    .io_deq_3_valid (io_read_3_valid),
    .io_deq_3_bits  (io_read_3_bits)
  );
endmodule

