// Generated by CIRCT firtool-1.62.1
module TOP(
  input        clock,
               reset,
  input  [4:0] io_read_arch_idx_0,
               io_read_arch_idx_1,
               io_read_arch_idx_2,
               io_read_arch_idx_3,
  output [7:0] io_read_pyhsical_o_0,
               io_read_pyhsical_o_1,
               io_read_pyhsical_o_2,
               io_read_pyhsical_o_3,
  input  [4:0] io_write_arch_idx_0,
               io_write_arch_idx_1,
  input        io_write_en_0,
               io_write_en_1,
  input  [7:0] io_write_pyhsical_0,
               io_write_pyhsical_1,
  input        io_bak_en,
               io_rev_en
);

  rat rat (
    .clock                (clock),
    .reset                (reset),
    .io_read_arch_idx_0   (io_read_arch_idx_0),
    .io_read_arch_idx_1   (io_read_arch_idx_1),
    .io_read_arch_idx_2   (io_read_arch_idx_2),
    .io_read_arch_idx_3   (io_read_arch_idx_3),
    .io_read_pyhsical_o_0 (io_read_pyhsical_o_0),
    .io_read_pyhsical_o_1 (io_read_pyhsical_o_1),
    .io_read_pyhsical_o_2 (io_read_pyhsical_o_2),
    .io_read_pyhsical_o_3 (io_read_pyhsical_o_3),
    .io_write_arch_idx_0  (io_write_arch_idx_0),
    .io_write_arch_idx_1  (io_write_arch_idx_1),
    .io_write_en_0        (io_write_en_0),
    .io_write_en_1        (io_write_en_1),
    .io_write_pyhsical_0  (io_write_pyhsical_0),
    .io_write_pyhsical_1  (io_write_pyhsical_1),
    .io_bak_en            (io_bak_en),
    .io_rev_en            (io_rev_en)
  );
endmodule

